version: "2.4"

services:
  mongo:
    image: mongo:5.0
    restart: always
    hostname: mongo
    container_name: mongo
    mem_limit: 256m
    cpus: 1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=supersecurePass1
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb

  postgres:
      image: postgres:14.4
      hostname: postgres
      container_name: postgres
      restart: unless-stopped
      mem_limit: 128m
      cpus: 2
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: keycloak_pwd

  keycloak:
    image: quay.io/keycloak/keycloak:19.0
    hostname: keycloak
    container_name: keycloak
    restart: unless-stopped
    mem_limit: 1024m
    cpus: 4
    volumes:
      - ./themes/custom:/opt/keycloak/themes/autoenrollment
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak_pwd
      DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: xentric
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - postgres
    #command: -Dkeycloak.profile.feature.upload_scripts=enabled
    command: start-dev

volumes:
  mongodb:
  mongodb_config:
  postgres_data:

networks:
  default:
    name: alloxentric.com